name: tlr_member_flutter
description: "The Living Room Member App - Flutter version"
publish_to: 'none'

version: 1.2.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Navigation
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  
  # State Management
  provider: ^6.1.2
  
  # HTTP and API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  
  # Biometric Authentication
  local_auth: ^2.3.0
  
  # Image handling
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Barcode scanning
  mobile_scanner: ^5.0.0
  
  # Date and time
  intl: ^0.20.2
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # Push notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  
  # Device info
  device_info_plus: ^12.1.0
  
  # Permissions
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # JSON serialization
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
