// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVVSv2HyEeMFEjCGKRKlKF22blv5a2uzY',
    appId: '1:196848491465:web:dd28d41de0865488c6e618',
    messagingSenderId: '196848491465',
    projectId: 'tlr-member',
    authDomain: 'tlr-member.firebaseapp.com',
    storageBucket: 'tlr-member.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVVSv2HyEeMFEjCGKRKlKF22blv5a2uzY',
    appId: '1:196848491465:android:dd28d41de0865488c6e618',
    messagingSenderId: '196848491465',
    projectId: 'tlr-member',
    storageBucket: 'tlr-member.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVVSv2HyEeMFEjCGKRKlKF22blv5a2uzY',
    appId: '1:196848491465:ios:dd28d41de0865488c6e618',
    messagingSenderId: '196848491465',
    projectId: 'tlr-member',
    storageBucket: 'tlr-member.firebasestorage.app',
    iosBundleId: 'com.thelivingroomloja21.member',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVVSv2HyEeMFEjCGKRKlKF22blv5a2uzY',
    appId: '1:196848491465:ios:dd28d41de0865488c6e618',
    messagingSenderId: '196848491465',
    projectId: 'tlr-member',
    storageBucket: 'tlr-member.firebasestorage.app',
    iosBundleId: 'com.thelivingroomloja21.member',
  );
}
